# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e2984efe7df86560e8c24e9d907162fd9af44815533ff34b89f03f13ea15a019445744c24b8f82330a4e0abdd57408131e2ac27f4d8eca4a9e7d86edd48526cc

test:
  secret_key_base: 88515da6e4940b1af31eeaebd3fbaecf1e1de4f6b138807b2ccc025d4cea8374502c7a6f1d6f1007a91b9c8d30d9917e266d63708353dffd480d584223a4cf78

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
